In [6]:
import sys
import fastf1
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.config import *
from src.load_save_data import *
from src.preprocess_data import *
from src.explore_data import *
from src.feature_engineering import *
from src.performance_analysis import *

In [7]:
session = fastf1.get_session(YEAR, GRAND_PRIX, "Q")
session.load()

driver_1, driver_2 = get_drivers(session, TEAM)
segment = get_segment(session, driver_1, driver_2)
turns = get_turns(session)

try:
    lap_1, lap_2 = load_cache(YEAR, GRAND_PRIX, segment, driver_1, driver_2)
except Exception as e:
    print(f"Processed data for {YEAR} {GRAND_PRIX} {driver_1} and {driver_2} not found: {e}")

core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '6', '44', '23', '87', '10', '55', '14', '30', '22', '27', '5', '31', '7', '18']

Processed data for 2025 Japanese Grand Prix ALO and STR found in cache.
Driver 1: ALO, Driver 2: STR, Segment: Q1

In [8]:
priority_segments = find_priority_zones(lap_1, lap_2, feature_type="Segments")
display(priority_segments)

priority_turns = find_priority_zones(lap_1, lap_2, feature_type="Turns")
display(priority_turns)

    Segment  SegmentTime_ALO  SegmentTime_STR     Delta
0        14        13.862592        14.126416 -0.263824
1        16         2.396257         2.616059 -0.219802
2        15         6.732748         6.546150  0.186598
3        13         2.838488         2.949786 -0.111299
4         6         5.107480         5.201582 -0.094102
5        17         2.829998         2.917315 -0.087317
6         7         5.518506         5.603595 -0.085089
7         1         1.904494         1.987201 -0.082707
8         0         8.405504         8.475170 -0.069666
9        11         5.652513         5.705942 -0.053429
10        9         5.705121         5.749258 -0.044137
11       10         3.693266         3.650824  0.042443
12        4         2.572671         2.604495 -0.031824
13        5         2.503026         2.526397 -0.023371
14        3         1.998492         1.975426  0.023066
15       18         1.830465         1.843356 -0.012891
16       12         8.310457         8.318894 -0.008437
17        8         2.532638         2.527616  0.005022
18        2         3.942284         3.945518 -0.003234

    Turn  TurnTime_ALO  TurnTime_STR     Delta
0     16      5.145679      4.837478  0.308201
1     17      2.367664      2.585284 -0.217619
2      5      1.593337      1.394205  0.199132
3     14      2.775509      2.928122 -0.152614
4      6      1.801300      1.653006  0.148294
5      2      2.012193      2.072301 -0.060108
6      4      1.507092      1.456939  0.050153
7     13      1.781942      1.821848 -0.039906
8      7      1.331637      1.353549 -0.021912
9     10      1.290761      1.312186 -0.021425
10     8      1.208773      1.229143 -0.020370
11    18      1.383833      1.396844 -0.013011
12    11      4.888629      4.877712  0.010917
13     3      1.487866      1.498084 -0.010218
14     9      2.723001      2.714242  0.008760
15    12      1.377905      1.383683 -0.005778
16    15      1.148176      1.153356 -0.005180
17     1      1.251325      1.249592  0.001733

In [9]:
contributor_segments = find_feature_contributors(lap_1, lap_2, priority_segments, feature_type="Segments",)
display(contributor_segments)

contributor_turns = find_feature_contributors(lap_1, lap_2, priority_turns, feature_type="Turns",)
display(contributor_turns)

,Segment,Feature,Delta,MeanAbsDelta,Pearson,PearsonP,Spearman,SpearmanP,CorrelationStrength,Confidence,MagnitudeScore,DirectionConsistency,ContributorScore,Direction
0,0,MeanSpeed,2.027044,5.231090,-0.740253,0.000290,-0.656140,0.002282,0.698197,0.997718,0.387499,1.0,0.328274,higher for ALO
1,0,MaximumRPM,168.000000,277.526316,-0.368096,0.120999,-0.228271,0.347243,0.298183,0.652757,0.605348,1.0,0.256485,higher for ALO
2,0,MaximumSpeed,1.127771,5.082346,-0.332014,0.164913,-0.331579,0.165502,0.331797,0.834498,0.221900,1.0,0.123308,higher for ALO
3,0,StdRPM,13.646028,164.227103,-0.452480,0.051751,-0.166667,0.495266,0.309573,0.504734,0.083092,1.0,0.027461,higher for ALO
4,0,MeanRPM,62.845238,228.240881,-0.341836,0.152015,-0.045614,0.852896,0.193725,0.147104,0.275346,1.0,0.024176,higher for ALO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,18,LowestGear,0.000000,0.368421,-0.441683,0.058325,-0.513092,0.024664,0.477387,0.941675,0.000000,0.0,0.000000,similar
262,18,HighestGear,0.000000,0.157895,0.102792,0.675395,0.164508,0.500946,0.133650,0.324605,0.000000,0.0,0.000000,similar
263,18,MinimumRPM,57.000000,395.684211,0.155699,0.524449,-0.087719,0.721024,0.121709,0.278976,0.144054,0.0,0.000000,higher for ALO
264,18,MaximumRPM,-36.000000,277.526316,-0.368096,0.120999,-0.228271,0.347243,0.298183,0.652757,0.129717,0.0,0.000000,lower for ALO
265,18,StdRPM,-41.386236,164.227103,-0.452480,0.051751,-0.166667,0.495266,0.309573,0.504734,0.252006,0.0,0.000000,lower for ALO

,Turn,Feature,Delta,MeanAbsDelta,Pearson,PearsonP,Spearman,SpearmanP,CorrelationStrength,Confidence,MagnitudeScore,DirectionConsistency,ContributorScore,Direction
0,1,BrakingDuration,-0.168168,0.273824,-0.208508,0.406370,-0.388749,0.110853,0.298628,0.593630,0.614146,1.0,0.236724,lower for ALO
1,1,BrakingDistance,-8.586515,11.806458,-0.093893,0.710954,-0.280012,0.260418,0.186953,0.289046,0.727273,1.0,0.124758,lower for ALO
2,1,ExitSpeed,2.908020,7.608747,0.047417,0.851790,-0.116615,0.644932,0.082016,0.148210,0.382194,1.0,0.030645,higher for ALO
3,1,BrakingPoint,0.000000,3.219943,0.269278,0.279897,0.244232,0.328719,0.256755,0.671281,0.000000,0.0,0.000000,similar
4,1,EntrySpeed,6.181753,8.056220,-0.468864,0.049675,-0.048504,0.848430,0.258684,0.151570,0.767327,0.0,0.000000,higher for ALO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,17,EntrySpeed,1.074480,8.056220,-0.468864,0.049675,-0.048504,0.848430,0.258684,0.151570,0.133373,1.0,0.012722,higher for ALO
74,17,ExitSpeed,19.115637,7.608747,0.047417,0.851790,-0.116615,0.644932,0.082016,0.148210,2.512324,0.0,0.000000,higher for ALO
75,18,ApexSpeed,9.524327,4.906477,-0.536950,0.021579,-0.519092,0.027279,0.528021,0.972721,1.941174,1.0,1.442621,higher for ALO
76,18,EntrySpeed,10.529802,8.056220,-0.468864,0.049675,-0.048504,0.848430,0.258684,0.151570,1.307040,1.0,0.124677,higher for ALO
77,18,ExitSpeed,6.781754,7.608747,0.047417,0.851790,-0.116615,0.644932,0.082016,0.148210,0.891310,0.0,0.000000,higher for ALO

In [10]:
summary_segments = calculate_contributor_summary(priority_segments, contributor_segments, feature_type="Segments",)
display(summary_segments)
save_dataframe(
    summary_segments,
    "SegmentFeaturesContributors",
    YEAR,
    GRAND_PRIX,
    TEAM,
)

summary_turns = calculate_contributor_summary(priority_turns, contributor_turns, feature_type="Turns",)
display(summary_turns)
save_dataframe(
    summary_turns,
    "TurnFeaturesContributors",
    YEAR,
    GRAND_PRIX,
    TEAM,
)

,Segment,TimeDelta,PossibleMainContributor,ContributorScore,Direction
0,14,-0.263824,MeanSpeed,0.837268,higher for ALO
1,14,-0.263824,MinimumSpeed,0.607985,higher for ALO
2,14,-0.263824,StdSpeed,0.607449,lower for ALO
3,14,-0.263824,FullThrottlePercentage,0.260027,higher for ALO
4,14,-0.263824,MaximumSpeed,0.218675,higher for ALO
...,...,...,...,...,...
90,2,-0.003234,MinimumSpeed,0.452681,higher for ALO
91,2,-0.003234,StdSpeed,0.198941,lower for ALO
92,2,-0.003234,MeanSpeed,0.150837,higher for ALO
93,2,-0.003234,MeanRPM,0.023979,higher for ALO
94,2,-0.003234,MaximumRPM,0.001527,higher for ALO

    Turn  TimeDelta PossibleMainContributor  ContributorScore       Direction
0     16   0.308201            BrakingPoint          2.249694  higher for ALO
1     16   0.308201               ApexSpeed          0.826517   lower for ALO
2     16   0.308201              EntrySpeed          0.524705   lower for ALO
3     16   0.308201         BrakingDuration          0.389309   lower for ALO
4     16   0.308201               ExitSpeed          0.283923  higher for ALO
..   ...        ...                     ...               ...             ...
65     1   0.001733         BrakingDuration          0.236724   lower for ALO
66     1   0.001733         BrakingDistance          0.124758   lower for ALO
67     1   0.001733               ExitSpeed          0.030645  higher for ALO
68     1   0.001733            BrakingPoint          0.000000         similar
69     1   0.001733              EntrySpeed          0.000000  higher for ALO

[70 rows x 5 columns]