In [1]:
import sys
import fastf1
from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.config import *
from src.load_save_data import *
from src.preprocess_data import *
from src.explore_data import *
from src.feature_engineering import *

In [2]:
session = fastf1.get_session(YEAR, GRAND_PRIX, "Q")
session.load()

driver_1, driver_2 = get_drivers(session, TEAM)
segment = get_segment(session, driver_1, driver_2)
turns = get_turns(session)

try:
    lap_1, lap_2 = load_cache(YEAR, GRAND_PRIX, segment, driver_1, driver_2)
except Exception as e:
    print(f"Processed data for {YEAR} {GRAND_PRIX} {driver_1} and {driver_2} not found: {e}")

req         WARNING 	DEFAULT CACHE ENABLED! (99.93 MB) C:\Users\joseg\AppData\Local\Temp\fastf1

core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '12', '6', '44', '23', '87', '10', '55', '14', '30', '22', '27', '5', '31', '7', '18']

Processed data for 2025 Japanese Grand Prix ALO and STR found in cache.
Driver 1: ALO, Driver 2: STR, Segment: Q1

In [ ]:
possible_contributors = find_main_contributors(lap_1, lap_2, feature_type="Turns", top_n=6)
display(possible_contributors)

,Feature,MeanAbsDelta,Pearson,PearsonP,Spearman,SpearmanP,CorrelationStrength,Confidence,MagnitudeScore,ContributorScore
0,ApexSpeed,4.906500,-0.537079,0.021542,-0.519092,0.027279,0.528085,0.972721,0.415576,21.347315
1,BrakingDistance,11.806500,-0.093334,0.712605,-0.280012,0.260418,0.186673,0.287395,1.000000,5.364884
2,BrakingPoint,3.219875,0.269438,0.279600,0.244232,0.328719,0.256835,0.671281,0.272721,4.701929
3,EntrySpeed,8.056056,-0.470564,0.048742,-0.048504,0.848430,0.259534,0.151570,0.682341,2.684155
4,ExitSpeed,7.608722,0.049624,0.844969,-0.116615,0.644932,0.083120,0.155031,0.644452,0.830447
5,BrakingDuration,0.273875,-0.208618,0.406117,-0.388749,0.110853,0.298683,0.593883,0.023197,0.411475

In [ ]:
possible_contributors = find_main_contributors(lap_1, lap_2, feature_type="Segments", top_n=8)
display(possible_contributors)

,Feature,MeanAbsDelta,Pearson,PearsonP,Spearman,SpearmanP,CorrelationStrength,Confidence,MagnitudeScore,ContributorScore
0,MaximumRPM,277.526316,-0.368471,0.120591,-0.228271,0.347243,0.298371,0.652757,0.701383,13.660403
1,MinimumRPM,395.684211,0.157249,0.520277,-0.087719,0.721024,0.122484,0.278976,1.000000,3.417019
2,MeanRPM,228.240895,-0.341685,0.152208,-0.045614,0.852896,0.193649,0.147104,0.576826,1.643181
3,FullThrottlePercentage,9.933526,-0.391559,0.097344,-0.424674,0.069933,0.408117,0.902656,0.025105,0.924828
4,MeanThrottle,5.291842,-0.556855,0.013267,-0.492982,0.031982,0.524919,0.968018,0.013374,0.679569
5,LowestGear,0.368421,-0.441958,0.058151,-0.513092,0.024664,0.477525,0.941849,0.000931,0.041877
6,HighestGear,0.157895,0.102519,0.676213,0.164508,0.500946,0.133514,0.323787,0.000399,0.001725
7,NumberOfShifts,0.421053,-0.032162,0.896007,-0.036920,0.880719,0.034541,0.103993,0.001064,0.000382